### ISSUE TITLE
Help understanding the main differences between this project and xhyve

### ISSUE THREAD

**Issue by asimpletune** [docker/hyperkit#102]
Hi, I'm just getting into hyperkit and I was hoping someone could just briefly say in a few words what the main differences between this project and xhyve are? Thank you!

**Comment by rneugeba** [comment]
HyperKit was originally derived from xhyve but we have extended it with a number of features and fixes to stability. New features include things like being able to run it with networking not requiring root (via VPNKit), support for virtio socket devices, support for qcow2 disk images (with trim support) etc. We also fixed a bunch of issues around waking up after sleep etc.

Does that answer your question?

**Comment by asimpletune** [comment]
Yes, that's exactly what I was looking for, thank you!
