### ISSUE TITLE
qcow2 file seems to reach a limit.

### ISSUE THREAD

**Issue by Adamantish** [docker/hyperkit#103]
I don't know lots about hypervisor. If there is a default limit to its VM space why can't this be set through hyperkit? Or can it? I have [someone advising me](http://stackoverflow.com/questions/42703481/why-has-docker-volume-run-out-of-space) to go in and resize the qcow2 file directly (it's currently at 60.8Gb which is mostly the database volume)

**Comment by ijc25** [comment]
Management of qcow files is out of scope for hyperkit, it just uses them as disk backing images.

It looks like you are using docker for mac, in which case the correct place to report issues is https://github.com/docker/for-mac. There are already some issues on this topic. You will likely find https://github.com/docker/for-mac/issues/371#issuecomment-262826610 useful if you want to customise the size of the disk (sadly it is still not hooked up in the UI), I'd appreciate it if you would let whoever was telling you go and do it directly about this too.

**Comment by Adamantish** [comment]
@ijc25 Thanks very much. Forgive my ignorance.
