### ISSUE TITLE
Bhyve unneeded code?

### ISSUE THREAD

**Issue by thebsdbox** [docker/hyperkit#22]
The `consport.c` and the `-b` flag code along with the `init_bvmcons()` code is redundant as this should (I think) always make use of lpc device emulation handles by `uart_emul.c` for tty support.. therefore never using the bhyve virtual machine console that is exposed through `consport.c`

I've already tested that this isn't needed, from the xhyve source tree on the mac.

**Comment by ijc25** [comment]
While it might not be needed in the common case a guest could still choose to use this mechanism though I think?

For example if you were brining up a new OS kernel it can be quite handy to have a lowlevel way to get bytes out of the VM (esp from low level asm) without needing to e.g. configure a UART device first. For example IIRC the UEFI implementation referenced in #10 can be configured to output to this console, I think that's what [`DebugPrint`](https://github.com/freebsd/uefi-edk2/blob/bhyve/UDK2014.SP1/BhyvePkg/Csm/BhyveCsm16/Printf.c#L892) in that code is doing (I can't actually vouch that it works as intended in the context of hyperkit mind).

IOW I don't think it is harmful to have this code sitting around for the odd occasion it might be useful to someone. Unless you are saying (and I don't think you are) that code is fundamentally unworkable in hyperkit for some reason?

**Comment by thebsdbox** [comment]
Well from bhyve itself:

```-b		 Enable a low-level console device supported by FreeBSD	ker-
		 nels compiled with device bvmconsole.	This option will be
		 deprecated in a future version.
```

It is capable to alternatively used gdb for low level output, or output to a term or even a `tmux` or `screen` file descriptor.

**Comment by ijc25** [comment]
So running FreeBSD in hyperkit would be able to use this device, which is good.

I'm afraid I don't see a compelling reason to remove this code right now.

**Comment by thebsdbox** [comment]
Bit of confusion here, this is an output method for hyperkit itself regardless of what operating system it's trying to run. In order for this code to work, the physical operating system would need to have support for a bvmconsole (so Docker for OSX would need to install a kext that exposed a /dev/bvmcons, which unless someone is writing probably won't happen)..

The`-b`flag and the `consport.c` code will only ever work if you were to run hyperkit on FreeBSD and had loaded the bvmcons kernel module, it could then use that as an output source for you virtual machine. However, this is being removed in the next releases of FreeBSD as the TTY or file descriptor methods for guest output are sufficient. 

Regardless, i've tested this just now on OSX and the inout.c won't care if a bvmcons device isn't present.. it's just dead code.

**Comment by ijc25** [comment]
`src/consport.c` takes I/O done by the guest to port 0x220 and proxies it into a host tty. It makes no use at all of any `bvmconsole` driver. For `src/consport.c` to be useful what is needed is a guest which does I/O to port 0x220.

`/dev/bvmconsole` is a (FreeBSD) guest side console driver which exposes a console which is backed by I/O to port 0x220. Any other OS could in principal also use port 0x220 for lowlevel debug I/O, as I've previously mentioned the UEFI port does that.

**Comment by thebsdbox** [comment]
OK, i'll close this. 
 
Would it make sense to have the I/O port configurable, or always leave it to the static value?

Thanks.
