### ISSUE TITLE
Feature request: USB driver pass through 

### ISSUE THREAD

**Issue by joeblew99** [docker/hyperkit#40]
I have to talk to all these smart card readers over USB.
I don't want to support win, osx, Linux plus all the USB drivers. I have 12 readers, so I end up with 12 x 3 = 36 drivers.

So run it all on linux as a docker guest. That has only the Linux USB drivers for each of the 12 reader types.

But it does not work when I tried a test.

Also i don't want to flag privileged mode and drop my pants.

Any ideas. Is this in the your boiling the ocean department still ?

I have the exact same use case for the Yubi key aspects also btw

**Comment by avsm** [comment]
Any reason this has been closed?  We could keep it open as a feature request.
