### ISSUE TITLE
Wrong location of the ramdisk in kexec

### ISSUE THREAD

**Issue by zchee** [docker/hyperkit#63]
In https://github.com/mist64/xhyve/issues/116, VinDuv(no mention because noisy) said

> The initramfs is actually corrupted by the Linux self-decompression mechanism. The decompressed kernel is written (in this case) from address 0x01000000 (16MB) to 0x0210c388 (~33MB). xhyve puts the initramfs at 0x01343000 (19MB), which gets overwritten.
> "Adding a sufficient offset to ramdisk_start in kexec.c allows the installer to start successfully. I have not tested it furthe"

Yes, `kexec.c` source have a wrong point.
I tried another kernel such as `minikube-iso`, it will fail on

```bash
Initramfs unpacking failed: junk in compressed archive
```

`ramdisk_start` variable was defined `ALIGNUP((kernel.base + kernel.size), 0x1000ull);`, but if use large kernel size, this start memory size is small.

This diff is tentative. `0x210c388ull` variable is unfounded. (I know, very ugly. it's not correct `ALIGNUP`.)
But it will work on the larger size kernel than `boot2docker.iso`.

```diff
diff --git a/src/firmware/kexec.c b/src/firmware/kexec.c
index 61aeebb..a5ee627 100644
--- a/src/firmware/kexec.c
+++ b/src/firmware/kexec.c
@@ -184,7 +184,7 @@ kexec_load_ramdisk(char *path) {
    sz = (size_t) ftell(f);
    fseek(f, 0, SEEK_SET);

-   ramdisk_start = ALIGNUP((kernel.base + kernel.size), 0x1000ull);
+   ramdisk_start = ALIGNUP((kernel.base + kernel.size), 0x210c388ull);

    if ((ramdisk_start + sz) > memory.size) {
        /* not enough memory */
```

I was read the source a little, but I could not be to know the correct value.
(related the linux initramfs specification? or other? Sorry, I don't know.)

Do you have any idea? or have the information of any specification?
Thanks.

ref: https://github.com/coreos/minikube-iso/issues/17#issuecomment-250664776

**Comment by ijc25** [comment]
> have the information of any specification?

Please check `Documentation/x86/boot.txt` in the Linux kernel repository, this should IIRC provide guidance on load addresses.

**Comment by zchee** [comment]
@ijc25 Thanks advice. I had previously seen it, but try to read again.
Just in case, It means add some flag to *Kernel boot command-line parameter*(console options, e.g. `loglevel=7`)?

**Comment by ijc25** [comment]
@zchee that document should include sufficient info to allow hyperkit to choose a better initramfs load address, to minimise the chance of overlap (IIRC it includes fields in the header which give the max allowable address, and loading the initramfs as high as possible ought to avoid these sorts of issues).

I'm not sure what you are asking wrt command-line parameters, there should be no need for such things to fix this issue.

**Comment by zchee** [comment]
@ijc25 Ah, I understand.
Yes, that doc has the detail of boot file header data. Including initramfs information too.

But, sorry, I'm not good at English... question again :(
I want to fix this problem based on `x86/boot.txt` documents.
Now, which one do you think the cause of `Initramfs unpacking failed` problem?

- `kexec.c` is fine, the way of make iso(or header data) is wrong.
- iso is fine, `kexec.c` is a little wrong. Should fix `kexec.c` to the better parse method.

**Comment by ijc25** [comment]
It seems more likely that `kexec.c` should be adjusted to make better choices WRT to the address it chooses to load the initramfs to. I was expecting that `x86/boot.txt` would provide enough guidance as to what a better mechanism for choosing the address would be.

To be a little more specific, but having not dug into this properly (so might be misguided) I think `boot.txt` describes some header fields around the maximum supported initramfs load address. So a good choice for `kexec.c` to make would be to load at `min(amount of RAM given to VM, maximum address supported by the kernel image) - size of initrd)` the answer would also need to be rounded _down_ to a suitable alignment.

There is one slight complication since the guest RAM may not be completely contiguous. See `xh_vm_setup_memory` where it is split low and high memory (this is to ensure there is some MMIO space below 4GB). You'd want to avoid loading the initramfs into the whole for example. Once simple way to avoid that would be to load to the top of the lowmem region rather than total ram. e.g. 
`min(amount of RAM given to VM, maximum address supported by the kernel image, lowmem limit) - size of initrd)`

**Comment by zchee** [comment]
@ijc25 Thanks for a polite reply. I totally understand you said meaning.

And understand you suggests mechanism too.
I know `xh_vm_setup_memory` behavior, so I also think `min(amount of RAM given to VM, maximum address supported by the kernel image, lowmem limit) - size of initrd)` is better.

I will more read that document and GNU/Linux kernel source.
Like the Docker for Mac, There is also a way to use uefi(bootrom) boot, but I will try to fix it.
Thanks for good reference.

**Comment by dlorenc** [comment]
I haven't gotten to try this yet other than compiling, but might something like this work?
https://github.com/dlorenc/libhyperkit/commit/249966ac29bc147afda731cebbe58d18ee46fef2

My reading of boot.txt indicates that we can use this address to start the ramdisk:

> Field name:	initrd_addr_max
> Type:		read
> Offset/size:	0x22c/4
> Protocol:	2.03+
> 
>   The maximum address that may be occupied by the initial
>   ramdisk/ramfs contents.  For boot protocols 2.02 or earlier, this
>   field is not present, and the maximum address is 0x37FFFFFF.  (This
>   address is defined as the address of the highest safe byte, so if
>   your ramdisk is exactly 131072 bytes long and this field is
>   0x37FFFFFF, you can start your ramdisk at 0x37FE0000.)

**Comment by zchee** [comment]
@dlorenc Oh, It seems to typo(lacking) `i`...?
I will try to test it.

@ijc25 What do you think about it?

**Comment by zchee** [comment]
Ah, it a wrong variable name for sure.
but that fix can't boot tiny core linux.
I'll more comment later.

**Comment by ijc25** [comment]
@dlorenc I think your
```
ramdisk_start = ALIGNUP(zp->setup_header.initrd_addr_max - sz, 0x100ull);
```

Needs to be `ALIGNDOWN` (which may need to be added), otherwise the end of the initrd might go past the address limit. It might alternatively be sufficient to round up the size before subtracting it from the max address.

**Comment by zchee** [comment]
@ijc25 I tested with adding you suggests `ALIGNDOWN()`, but still fail boot depending on the size of the kernel. Their values seem too large.
I will more debug it.

**Comment by dlorenc** [comment]
This code from qemu looks relevant: https://github.com/qemu/openbios/blob/master/arch/sparc32/linux_load.c

**Comment by zchee** [comment]
I also reading qemu's standalone boot loader. and almost figured out.

I will backport some logic, and will create pull request.

**Comment by ijc25** [comment]
@dlorenc that path says `sparc32` in it, although the file itself refers to i386 a lot. Not sure what's going on there, maybe sparc Linux forked the x86 vmlinuz binary format waaay back -- I'd be wary of trusting it as a source of truth for an x86 fix too much though. (also, that code is from openbios, which is including in qemu but not actually qemu AFAICT).

@zchee awesome, thanks. Please pay attention to licensing if copying things from QEMU. Hyperkit is BSD licensed but QEMU is a mix of BSD and GPL (and possibly others). Please avoid introducing GPL code into Hyperkit (it might be that you feel it is appropriate to use such code as a reference to gather "facts" about the binary interface, but you'll need to rewrite from scratch and not literally copy).

**Comment by dlorenc** [comment]
> @dlorenc that path says sparc32 in it, although the file itself refers to i386 a lot. Not sure what's going on there, maybe sparc Linux forked the x86 vmlinuz binary format waaay back -- I'd be wary of trusting it as a source of truth for an x86 fix too much though. (also, that code is from openbios, which is including in qemu but not actually qemu AFAICT).

Sorry, the same code is in the amd64 and x86 directories as well, I just grabbed the wrong link:
https://github.com/qemu/openbios/blob/master/arch/x86/linux_load.c

**Comment by zchee** [comment]
@ijc25 reply for license issue.
Yes, I don't like the introducing GPL code into Hyperkit.
I was gathering "facts" about the binary interface from qemu sources and copied one or two comments(note). but almost write scratch.

Is my PR have a problem?

**Comment by ijc25** [comment]
I wrote the above comment about licensing before I'd seen that you had raised a PR and just wanted to head off one common pitfall. Having seen the PR now AFAICT it looks fine from a license perspective.

Closing this issue in favour of https://github.com/docker/hyperkit/pull/66.

**Comment by zchee** [comment]
@ijc25 got it. Thanks :)
