### ISSUE TITLE
Hyperkit leaks

### ISSUE THREAD

**Issue by jaoa25** [docker/hyperkit#67]
Good afternoon,

I noticed(and could read it in other issues) that Hyperkit is having trouble freeing up memory when it have been allocated by the linux kernel which annoys me big time. Do any tickets exists for fixing that issue? Or tickets in underlaying projects that might lead to the issue being fixed in Hyperkit? Or basically anything that would get me closer to taking a stab at fixing it?

**Comment by ijc25** [comment]
Sounds from your terse description like you are referring to something like the issues described in https://github.com/docker/for-mac/issues/178 and https://github.com/docker/for-mac/issues/781? That is the OSX process is actually using that memory (as guest RAM) and has not "leaked" in the normal sense.

The [first comment on the former](https://github.com/docker/for-mac/issues/178#issuecomment-238509543) is basically an accurate summary of where we are right now with this. Only if you are seeing either actual memory leaks (that is, memory which the hypervisor has actually lost track of) or memory allocated to the hyperkit process which is _unswappable_ (which would manifest as the `RSS` remaining high even when the VM is idle and there are other memory pressures in the system) would we currently consider this an issue. If you are aware of either scenario occurring then we would be grateful of the details.

For those who are concerned about _swappable_ memory allocated to virtual machines (i.e. the `VSZ` of the process) the usual answer is ballooning, which in this context would start with an implementation of the virtio-balloon backend in hyperkit. However ballooning functionality in the hypervisor is only a building block and other higher level code would also be needed to manage this functionality in a way which did not compromise functionality/stability/reliability of projects which use hyperkit (or to put it more concretely and avoid giving false hope/commitment: adding ballooning functionality in hyperkit would not automatically mean it would be activated by Docker for mac, it would need careful evaluation and integration work by the docker for mac team first).

We currently don't have any plans to work on anything related to this but if, given the caveats expressed here, you are still interested then PRs to implement virtio-ballooning in hyperkit would be welcome.

**Comment by jhorwit2** [comment]
@ijc25 I've had issues when memory appears to be full docker quits responding to various commands (like `ps` or being able to download images). The only way to fix it is the restart the process so memory goes back down.

**Comment by ijc25** [comment]
@jhorwit2 Please open a new ticket against docker/for-mac about the issue you are seeing including a diagnostic bundle upload etc. Easiest way to do that is to use the "Diagnostics & Feedback" item in the Whale menu.

Closing this issue since there has been no further response from the OP.

**Comment by kyprifog** [comment]
Ive noticed this happening to me sometimes when i've accidentally tried to interact with a really large image.  Restarting docker, and clearing out images doesn't seem to help.  Doing a factory restart on docker does.  I think it tries to access some of the same volume information between restarts.

**Comment by rn** [comment]
@kyprifog please file an issue on docker/for-mac unless you are certain that this is an issue with hyperkit itself. If you think it is hyperkit itself, please provide more details.
