### ISSUE TITLE
proposal: coding styleguide (or tools)

### ISSUE THREAD

**Issue by zchee** [docker/hyperkit#71]
Hi,
This is not a criticism, it is the proposal.

I was some debug and wrote a fixed code for `kexec.c`, and reads other files now.
As https://github.com/docker/hyperkit/pull/65, I think `whitespace = fix` is good, but still `space` and `tab` has mixed on code indent.

i.e. https://github.com/docker/hyperkit/blob/master/src/hyperkit.c#L170-L173
The line of 170 is space, but L171-173 is tab...

I don't mind either way(space or tab), but can we unify code style by any formatting tools such as `clang-format`?(I think `clang-format` is modern and generally)
For contributors who want to add any new features, hyperkit maintainer, This problem is no good for anybody.

I'm not going to blame(criticism?) the original(xhyve), but hyperkit became OSS project by the Docker Inc.
If we want to smoothly develop in the future, I think the code style should be unified.

**Comment by rneugeba** [comment]
The general coding style should follow style(9) from FreeBSD as the majority of the code is derived from it.

`clang-format` doesn't quite do the right thing, neither does `indent`

**Comment by dave-tucker** [comment]
A quick google found [this](https://groups.google.com/forum/#!topic/mailing.freebsd.hackers/p4qt2K683kQ) which suggests using [uncrustify](http://uncrustify.sourceforge.net/) with [this config](https://github.com/freebsd/pkg/blob/master/freebsd.cfg)

The thread contains a good discussion of the cases that aren't covered by that tool.

**Comment by zchee** [comment]
@rneugeba Ah, I see. Use FreeBSD style, use uncrustify(?) is no problem.
I want to just unified code styling only.
Do you have any plan?

**Comment by rneugeba** [comment]
@zchee I would advise against wholesale coding style changes uncrustify or similar. Ideally, we'd like to keep the bhyve derived code as close as possible to the original and the bhyve code in some areas does not necessarily comply with the BSD coding style to the dot (they are guidelines afterall).

There are, however, some obvious minor places for cleanup, but I'm not sure it's worth the effort going through them

**Comment by zchee** [comment]
@rneugeba Thanks for detail reply. I understand.
Also, thanks again new PR. That became clear to me.
