### ISSUE TITLE
Hyperkit segfaults if format=qcow is passed to it without qcow-config

### ISSUE THREAD

**Issue by rahulg** [docker/hyperkit#88]
Hyperkit segfaults if a qcow disk is used, but the `qcow-config` option is not explicitly passed to it.

Here's an example:

```
$ FLAGS="-A -s 0:0,hostbridge -s 31,lpc -l com1,stdio -m 4G -s 2:0,virtio-net"
```

This segfaults:
```
# com.docker.hyperkit $FLAGS -s "4,virtio-blk,file:///tmp/test.qcow2,format=qcow" -f "kexec,vmlinuz,initramfs.img,earlyprintk=serial console=ttyS0"
```

While this doesn't:
```
# com.docker.hyperkit $FLAGS -s "4,virtio-blk,file:///tmp/test.qcow2,format=qcow,qcow-config=" -f "kexec,vmlinuz,initramfs.img,earlyprintk=serial console=ttyS0"
```

I'm not sure if `qcow-config` is intended to be a mandatory option, but if it is, hyperkit should probably throw an error instead of segfaulting.

**Comment by ijc25** [comment]
I think it was supposed to be an optional thing rather than mandatory, @djs55 is that correct?

**Comment by djs55** [comment]
It was supposed to be optional-- I'll take a look.
