### ISSUE TITLE
Example that uses the 9p backend

### ISSUE THREAD

**Issue by copumpkin** [docker/hyperkit#95]
I see that in theory at least there's some 9p support in HyperKit, which is awesome, but I don't see any obvious examples of how to use it, in tests or anywhere else. Can someone point me in the right direction, or add something to the tests?

**Comment by copumpkin** [comment]
I see that at least in the current implementation, it expects to be plugged into a 9p server. In the longer term, it might be more user-friendly to allow users to run hyperkit and pass folders in to be shared and have the hyperkit executable take care of serving up the 9p stuff.

**Comment by ijc25** [comment]
Hi @copumpkin 

> I don't see any obvious examples of how to use it

It is (briefly) documented in the hyperkit man page (`hyperkit.1` in the repo). There's also a little bit of info in https://github.com/docker/hyperkit/pull/3 including links to some possible backends.

**Comment by copumpkin** [comment]
@ijc25 that makes sense, thanks. Any thoughts on whether incorporating 9p directly into the runner is planned? For now I'll run my own daemon, but it'd be nice not to need to do that. Makes it hard to run a short-lived VM inside a script if I need to set up concurrent processes and make sure to clean them up, etc.

**Comment by ijc25** [comment]
I'm not aware of anyone who is planning to implement such a thing.

**Comment by copumpkin** [comment]
Alright, thanks.
