### ISSUE TITLE
Allow more than 16 vCPUs

### ISSUE THREAD

**Issue by dsheets** [docker/hyperkit#96]
Currently <https://github.com/docker/hyperkit/blob/master/src/include/xhyve/vmm/vmm_common.h#L33> restricts the maximum number of vCPUs to 16. For compute-heavy workloads, this arbitrary restriction may be undesirable (see docker/for-mac#1144). This number is mainly used to size static arrays but, as @ijc25 notes, there may be work checking that ACPI tables are set up correctly to offer enough cores correctly.

**Comment by rneugeba** [comment]
`acpitbl.c` takes a number of CPU argument and scales the various ACPI tables and their content by it. So it may work...

**Comment by grehan-freebsd** [comment]
Just be aware of table sizing/overflow (http://docs.FreeBSD.org/cgi/mid.cgi?2ebbc1f9-4b1e-74f2-60fc-c0976b7924a1)

**Comment by rneugeba** [comment]
@grehan-freebsd thanks for the heads up!
